# Generated by Django 2.2.7 on 2019-11-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=15)),
                ('cnpj', models.CharField(blank=True, max_length=25)),
                ('placa', models.CharField(max_length=7)),
            ],
        ),
    ]
