# Generated by Django 2.2.7 on 2019-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20191112_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='combustivel',
            field=models.CharField(choices=[('A', 'Alcool'), ('G', 'Gasolina'), ('D', 'Diesel'), ('F', 'Flex')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fabricante',
            field=models.CharField(choices=[('Volkswagen', 'volkswagen'), ('FIAT', 'FIAT'), ('Chevrolet', 'Chevrolet'), ('General Motors', 'General Motors'), ('Hyundai-Kia', 'Hyundai-Kia'), ('Ford Motor', 'Ford Motor'), ('Renault-Nissan', 'Renault-Nissan'), ('Honda Motor', 'Honda Motor'), ('Mercedes', 'Mercedes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modelo',
            field=models.CharField(choices=[('H', 'Hatch'), ('S', 'Sedã'), ('U', 'SUV'), ('V', 'Van'), ('C', 'Picape')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='motor',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.8', '1.8'), ('2.0', '2.0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pintura',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Cinza', 'Cinza'), ('Prata', 'Prata'), ('Preto', 'Preto'), ('Dourado', 'Dourado'), ('Vermelho', 'Vermelho')], max_length=30),
        ),
    ]
