# Generated by Django 2.2.7 on 2019-11-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20191112_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='combustivel',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pintura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='placa',
        ),
    ]
