# Generated by Django 2.2.7 on 2019-11-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ano',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='combustivel',
            field=models.CharField(choices=[('A', 'Alcool'), ('G', 'Gasolina'), ('D', 'Diesel'), ('F', 'Flex')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='fabricante',
            field=models.CharField(choices=[('Volkswagen', 'volkswagen'), ('FIAT', 'FIAT'), ('Chevrolet', 'Chevrolet'), ('General Motors', 'General Motors'), ('Hyundai-Kia', 'Hyundai-Kia'), ('Ford Motor', 'Ford Motor'), ('Renault-Nissan', 'Renault-Nissan'), ('Honda Motor', 'Honda Motor'), ('Mercedes', 'Mercedes')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='modelo',
            field=models.CharField(choices=[('H', 'Hatch'), ('S', 'Sedã'), ('U', 'SUV'), ('V', 'Van'), ('C', 'Picape')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='motor',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.8', '1.8'), ('2.0', '2.0')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='pintura',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Cinza', 'Cinza'), ('Prata', 'Prata'), ('Preto', 'Preto'), ('Dourado', 'Dourado'), ('Vermelho', 'Vermelho')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='placa',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='carro',
            field=models.CharField(max_length=50),
        ),
    ]
