# Generated by Django 2.2.7 on 2019-11-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20191112_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('Pintura', 'Pintura'), ('Lanternagem', 'Lanternagem'), ('Mecanica', 'Mecanica'), ('Pintura/Lanternagem', 'Pintura/Lanternagem'), ('Pintura/Mecaninca', 'Pintura/Mecaninca'), ('Lanternagem/Mecanica', 'Lanternagem/Mecanica'), ('Pintura/Lanternagem/Mecanica', 'Pintura/Lanternagem/Mecanica')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='pecas',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='solucao',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
