# Generated by Django 2.2.7 on 2019-11-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20191112_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
