# Generated by Django 2.2.7 on 2019-11-15 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20191112_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_serv',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servico',
            name='combustivel',
            field=models.CharField(choices=[('Alcool', 'Alcool'), ('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Flex', 'Flex')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='fabricante',
            field=models.CharField(choices=[('Volkswagen', 'volkswagen'), ('FIAT', 'FIAT'), ('Chevrolet', 'Chevrolet'), ('General Motors', 'General Motors'), ('Hyundai-Kia', 'Hyundai-Kia'), ('Ford Motor', 'Ford Motor'), ('Renault', 'Renault'), ('Honda Motor', 'Honda Motor'), ('Mercedes', 'Mercedes'), ('Pegout', 'Pegeut')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='modelo',
            field=models.CharField(choices=[('Hatch', 'Hatch'), ('Sedã', 'Sedã'), ('SUV', 'SUV'), ('Van', 'Van'), ('Picape', 'Picape')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='motor',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.IntegerField(default=0),
        ),
    ]
